# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postcollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperVideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('goals', models.TextField()),
                ('how_to', models.TextField()),
                ('youtube_link', models.URLField()),
                ('image_link', models.URLField()),
                ('start', models.PositiveSmallIntegerField()),
                ('end', models.PositiveSmallIntegerField()),
                ('file', models.FileField(default='file/None/No-doc.pdf', upload_to='uploads/')),
                ('collection', models.ManyToManyField(to='postcollections.Collection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super Video Post',
                'verbose_name_plural': 'Super Video Posts',
            },
        ),
    ]
